// src/admin/pages/Users.jsx
import { useState } from "react";
import { User, Shield, Ban, Search, Eye, X, MoreVertical, Download } from "lucide-react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function Users() {
  const initialUsers = [
    { id: 1, name: "John Doe", email: "john@example.com", phone: "9876543210", role: "Customer", status: "Active" },
    { id: 2, name: "Alice Smith", email: "alice@example.com", phone: "9876501234", role: "Admin", status: "Active" },
    { id: 3, name: "Rahul Kumar", email: "rahul@example.com", phone: "9876598765", role: "Customer", status: "Blocked" },
  ];

  // Dummy orders mapped by userId
  const userOrders = {
    1: [
      { id: "ORD001", status: "Completed" },
      { id: "ORD002", status: "Pending" },
      { id: "ORD003", status: "Cancelled" },
    ],
    2: [{ id: "ORD004", status: "Completed" }],
    3: [
      { id: "ORD005", status: "Pending" },
      { id: "ORD006", status: "Pending" },
    ],
  };

  const [users, setUsers] = useState(initialUsers);
  const [search, setSearch] = useState("");
  const [roleFilter, setRoleFilter] = useState("All");
  const [statusFilter, setStatusFilter] = useState("All");
  const [viewUser, setViewUser] = useState(null);
  const [actionUser, setActionUser] = useState(null);

  // Toggle Admin role
  const handleToggleAdmin = (id) => {
    setUsers((prev) =>
      prev.map((u) =>
        u.id === id ? { ...u, role: u.role === "Admin" ? "Customer" : "Admin", status: "Active" } : u
      )
    );
    setActionUser(null);
  };

  // Toggle Block / Unblock
  const handleToggleBlock = (id) => {
    setUsers((prev) =>
      prev.map((u) =>
        u.id === id ? { ...u, status: u.status === "Active" ? "Blocked" : "Active" } : u
      )
    );
    setActionUser(null);
  };

  // Filter users
  const filteredUsers = users.filter((user) => {
    const matchesSearch =
      user.name.toLowerCase().includes(search.toLowerCase()) ||
      user.email.toLowerCase().includes(search.toLowerCase()) ||
      user.phone.includes(search);
    const matchesRole = roleFilter === "All" ? true : user.role === roleFilter;
    const matchesStatus = statusFilter === "All" ? true : user.status === statusFilter;
    return matchesSearch && matchesRole && matchesStatus;
  });

  // Count user orders by status
  const getOrderStats = (userId) => {
    const orders = userOrders[userId] || [];
    return {
      total: orders.length,
      completed: orders.filter((o) => o.status === "Completed").length,
      pending: orders.filter((o) => o.status === "Pending").length,
      cancelled: orders.filter((o) => o.status === "Cancelled").length,
    };
  };

  // Export user orders as CSV
  const exportUserOrdersCSV = (user) => {
    const orders = userOrders[user.id] || [];
    if (orders.length === 0) return alert("No orders found for this user.");

    const headers = ["Order ID", "Status"];
    const rows = orders.map((o) => [o.id, o.status]);

    const csvContent =
      "data:text/csv;charset=utf-8," +
      [headers.join(","), ...rows.map((r) => r.join(","))].join("\n");

    const link = document.createElement("a");
    link.href = encodeURI(csvContent);
    link.download = `Orders_${user.name.replace(/\s+/g, "_")}.csv`;
    link.click();
  };

  // Export user orders as PDF
  const exportUserOrdersPDF = (user) => {
  const orders = userOrders[user.id] || [];
  const doc = new jsPDF();

  // Title
  doc.setFontSize(16);
  doc.text("ADRS Technosoft - User Order Report", 14, 20);

  // Customer Info
  doc.setFontSize(12);
  doc.text(`User ID: ${user.id}`, 14, 35);
  doc.text(`Name: ${user.name}`, 14, 45);
  doc.text(`Email: ${user.email}`, 14, 55);
  doc.text(`Phone: ${user.phone}`, 14, 65);
  doc.text(`Role: ${user.role}`, 14, 75);
  doc.text(`Status: ${user.status}`, 14, 85);

  // Orders Table
  autoTable(doc, {
    startY: 95,
    head: [["Order ID", "Status"]],
    body: orders.map((o) => [o.id, o.status]),
  });

  // If no orders
  if (orders.length === 0) {
    doc.text("No orders found for this user.", 14, 100);
  }

  // Footer
  doc.setFontSize(10);
  doc.text("Generated by ADRS Technosoft", 14, doc.lastAutoTable ? doc.lastAutoTable.finalY + 20 : 120);

  // File name: "User_John_Doe_Orders.pdf"
  const safeName = user.name.replace(/\s+/g, "_");
  const fileName = `User_${safeName}_Orders.pdf`;

  doc.save(fileName);
};

  return (
    <div className="p-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-center mb-6 gap-3">
        <h1 className="text-2xl font-bold">Users</h1>

        {/* Filters */}
        <div className="flex flex-wrap gap-3 items-center">
          <div className="relative">
            <Search className="w-4 h-4 text-gray-400 absolute left-3 top-1/2 transform -translate-y-1/2" />
            <input
              type="text"
              placeholder="Search by name, email or phone"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="pl-9 pr-3 py-2 border rounded-lg text-sm focus:ring-2 focus:ring-brand"
            />
          </div>

          <select
            value={roleFilter}
            onChange={(e) => setRoleFilter(e.target.value)}
            className="px-3 py-2 border rounded-lg text-sm focus:ring-2 focus:ring-brand"
          >
            <option value="All">All Roles</option>
            <option value="Admin">Admin</option>
            <option value="Customer">Customer</option>
          </select>

          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="px-3 py-2 border rounded-lg text-sm focus:ring-2 focus:ring-brand"
          >
            <option value="All">All Status</option>
            <option value="Active">Active</option>
            <option value="Blocked">Blocked</option>
          </select>
        </div>
      </div>

      {/* Users Table */}
      <div className="overflow-x-auto bg-white rounded-xl shadow">
        <table className="min-w-full table-auto text-sm">
          <thead className="bg-gray-100 text-gray-600 uppercase text-xs">
            <tr>
              <th className="py-3 px-6 text-left">ID</th>
              <th className="py-3 px-6 text-left">Name</th>
              <th className="py-3 px-6 text-left">Email</th>
              <th className="py-3 px-6 text-left">Phone</th>
              <th className="py-3 px-6 text-left">Role</th>
              <th className="py-3 px-6 text-left">Status</th>
              <th className="py-3 px-6 text-center">Actions</th>
            </tr>
          </thead>
          <tbody className="text-gray-700">
            {filteredUsers.length > 0 ? (
              filteredUsers.map((user) => (
                <tr key={user.id} className="border-b hover:bg-gray-50">
                  <td className="py-3 px-6">{user.id}</td>
                  <td className="py-3 px-6 font-medium flex items-center gap-2">
                    <User className="w-4 h-4 text-gray-500" />
                    {user.name}
                  </td>
                  <td className="py-3 px-6">{user.email}</td>
                  <td className="py-3 px-6">{user.phone}</td>
                  <td className="py-3 px-6">{user.role}</td>
                  <td className="py-3 px-6">
                    <span
                      className={`px-2 py-1 rounded-full text-xs font-semibold ${
                        user.status === "Active"
                          ? "bg-green-100 text-green-700"
                          : "bg-red-100 text-red-700"
                      }`}
                    >
                      {user.status}
                    </span>
                  </td>
                  <td className="py-3 px-6 text-center relative">
                    <button
                      onClick={() => setActionUser(actionUser === user.id ? null : user.id)}
                      className="p-2 rounded-full hover:bg-gray-200"
                    >
                      <MoreVertical className="w-5 h-5 text-gray-600" />
                    </button>

                    {/* Dropdown */}
                    {actionUser === user.id && (
                      <div className="absolute right-0 mt-2 w-40 bg-white shadow-lg border rounded-lg z-10">
                        <button
                          onClick={() => {
                            setViewUser(user);
                            setActionUser(null);
                          }}
                          className="w-full text-left px-4 py-2 hover:bg-gray-100 flex items-center gap-2 text-sm"
                        >
                          <Eye className="w-4 h-4 text-blue-600" /> View
                        </button>
                        <button
                          onClick={() => handleToggleAdmin(user.id)}
                          className="w-full text-left px-4 py-2 hover:bg-gray-100 flex items-center gap-2 text-sm"
                        >
                          <Shield className="w-4 h-4 text-purple-600" />{" "}
                          {user.role === "Admin" ? "Remove Admin" : "Make Admin"}
                        </button>
                        <button
                          onClick={() => handleToggleBlock(user.id)}
                          className="w-full text-left px-4 py-2 hover:bg-gray-100 flex items-center gap-2 text-sm"
                        >
                          <Ban
                            className={`w-4 h-4 ${
                              user.status === "Active" ? "text-red-600" : "text-green-600"
                            }`}
                          />{" "}
                          {user.status === "Active" ? "Block" : "Unblock"}
                        </button>
                      </div>
                    )}
                  </td>
                </tr>
              ))
            ) : (
              <tr>
                <td colSpan="7" className="py-6 text-center text-gray-500 italic">
                  No users found.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {/* View User Modal */}
      {viewUser && (
        <div className="fixed inset-0 flex items-center justify-center bg-black bg-opacity-40 z-50">
          <div className="bg-white rounded-lg shadow-lg w-full max-w-2xl p-6 relative">
            <button
              onClick={() => setViewUser(null)}
              className="absolute top-2 right-2 text-gray-500 hover:text-red-600"
            >
              <X size={22} />
            </button>

            <h2 className="text-xl font-bold mb-4">User Details</h2>
            <div className="space-y-2 text-sm">
              <p><span className="font-semibold">ID:</span> {viewUser.id}</p>
              <p><span className="font-semibold">Name:</span> {viewUser.name}</p>
              <p><span className="font-semibold">Email:</span> {viewUser.email}</p>
              <p><span className="font-semibold">Phone:</span> {viewUser.phone}</p>
              <p><span className="font-semibold">Role:</span> {viewUser.role}</p>
              <p><span className="font-semibold">Status:</span> {viewUser.status}</p>

              {/* Orders summary */}
              <h3 className="mt-4 font-semibold">Order Summary:</h3>
              {(() => {
                const stats = getOrderStats(viewUser.id);
                return (
                  <>
                    <ul className="list-disc ml-6 space-y-1 mb-3">
                      <li>Total Orders: {stats.total}</li>
                      <li className="text-green-600">Completed: {stats.completed}</li>
                      <li className="text-yellow-600">Pending: {stats.pending}</li>
                      <li className="text-red-600">Cancelled: {stats.cancelled}</li>
                    </ul>

                    {/* Orders table */}
                    <div className="overflow-x-auto bg-gray-50 rounded-lg shadow-inner p-2">
                      <table className="min-w-full text-xs border-collapse">
                        <thead className="bg-gray-200 text-gray-600 uppercase">
                          <tr>
                            <th className="px-3 py-2 text-left">Order ID</th>
                            <th className="px-3 py-2 text-left">Status</th>
                          </tr>
                        </thead>
                        <tbody>
                          {userOrders[viewUser.id] && userOrders[viewUser.id].length > 0 ? (
                            userOrders[viewUser.id].map((o) => (
                              <tr key={o.id} className="border-b">
                                <td className="px-3 py-2 font-medium">{o.id}</td>
                                <td
                                  className={`px-3 py-2 font-semibold ${
                                    o.status === "Completed"
                                      ? "text-green-600"
                                      : o.status === "Pending"
                                      ? "text-yellow-600"
                                      : "text-red-600"
                                  }`}
                                >
                                  {o.status}
                                </td>
                              </tr>
                            ))
                          ) : (
                            <tr>
                              <td colSpan="2" className="text-center py-2 text-gray-500 italic">
                                No orders found
                              </td>
                            </tr>
                          )}
                        </tbody>
                      </table>
                    </div>
                  </>
                );
              })()}

              {/* Download buttons */}
              <div className="flex gap-3 mt-4">
                <button
                  onClick={() => exportUserOrdersCSV(viewUser)}
                  className="flex items-center gap-2 px-3 py-2 bg-green-600 text-white text-sm rounded-lg hover:bg-green-700 transition"
                >
                  <Download className="w-4 h-4" /> CSV
                </button>
                <button
                  onClick={() => exportUserOrdersPDF(viewUser)}
                  className="flex items-center gap-2 px-3 py-2 bg-blue-600 text-white text-sm rounded-lg hover:bg-blue-700 transition"
                >
                  <Download className="w-4 h-4" /> PDF
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
